project:
  type: website
  output-dir: _site
  render:
    - slides/textlab-ringvorlesung.qmd
  resources:
    - index.html

website:
  title: "TextLab in den Digital Humanities"

lang: de
bibliography: references.bib
link-citations: true

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    number-sections: false
    link-external-newwindow: true

execute:
  freeze: auto
